version: "3"
services:
  binary1:
    build:
      context: .
    image: reverse
    container_name: slashroot7-lazy
    entrypoint: socat tcp-listen:8000,reuseaddr,fork exec:/home/app/chall
    volumes:
      - "./lazy:/home/app"
    ports:
      - "2021:8000"

  # binary2:
  #   build:
  #     context: .
  #   image: reverse
  #   container_name: slashroot6-solo-lord
  #   entrypoint: socat tcp-listen:8000,reuseaddr,fork exec:/home/app/chall
  #   volumes:
  #     - "./solo_lord:/home/app"
  #   ports:
  #     - "2022:8000"

  # binary3:
  #   build:
  #     context: .
  #   image: reverse
  #   container_name: slashroot6-hello
  #   entrypoint: socat tcp-listen:8000,reuseaddr,fork exec:/home/app/chall
  #   volumes:
  #     - "./hello:/home/app"
  #   ports:
  #     - "2023:8000"
