version: "3"
services:
  binary1:
    build:
      context: .
    image: reverse
    container_name: slashroot7-lazy
    entrypoint: socat tcp-listen:8000,reuseaddr,fork exec:/home/app/chall
    volumes:
      - "./lazy:/home/app"
    ports:
      - "2021:8000"
